# Jekyll Resume Theme

# Site settings
title: Ezgi Sen Resume
email: ezgi.sen@dkfz-heidelberg.de
description: Graduate student @DKFZ
baseurl: ""
url: ""
name: Ezgi Sen

location: Heidelberg, Germany
job:  M.Sc. student in Cancer Biology
twitter_username: ezgiisenn98
github_username:  ezgiisenn
email_address: ezgi.sen@dkfz-heidelberg.de

# Build settings
markdown: kramdown
