# Jekyll Resume Theme

# Site settings
title: Ezgi Sen Resume
email: ezgi.sen@dkfz-heidelberg.de
description: Cancer Biology M.Sc. student @DKFZ
baseurl: ""
url: ""
name: Ezgi Sen

location: Heidelberg, Germany
languages:
twitter_username: ezgiisenn98
github_username:  ezgiisenn
email_address: ezgi.sen@dkfz-heidelberg.de

# Build settings
markdown: kramdown
